<?php

namespace AppBundle\Repository;

/**
 * goederenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class goederenRepository extends \Doctrine\ORM\EntityRepository
{
}
