<?php

namespace AppBundle\Repository;

/**
 * leverancierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class leverancierRepository extends \Doctrine\ORM\EntityRepository
{
}
