<?php

namespace AppBundle\Repository;

/**
 * magazijnRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class magazijnRepository extends \Doctrine\ORM\EntityRepository
{
}
